# Generated by Django 4.1.1 on 2022-10-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(upload_to='promoters/'),
        ),
    ]
